# SPDX-FileCopyrightText: 2026 Samuel Wu
#
# SPDX-License-Identifier: 0BSD

version = "1.1"

["whatdepends"]
type = "command"
attached_command = "repoquery"
descr.C = "Alias for 'repoquery --installed --whatdepends=<package>'"
complete = true

[[whatdepends.required_values]]
value_help.C = "CAPABILITY,..."
descr.C = "Limit to packages that depend any of <capabilities>."

[[whatdepends.attached_named_args]]
id_path = "repoquery.installed"

[[whatdepends.attached_named_args]]
id_path = "repoquery.whatdepends"
value="${1}"
